# Generated by Django 4.2 on 2024-10-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionjurado',
            name='fecha_evaluacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practica',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_supervisadas', to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='practica',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('EVALUADA', 'Evaluada')], default='PENDIENTE', max_length=20),
        ),
    ]
