# Generated by Django 4.2 on 2024-11-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_usuario_carrera_remove_usuario_ciclo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observaciones', models.TextField()),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado')], max_length=20)),
                ('practica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.practica')),
            ],
        ),
    ]
