# Generated by Django 4.2 on 2024-11-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_asistencia_presente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='presente',
            field=models.CharField(choices=[('ASISTIO', 'Asistió'), ('TARDANZA', 'Tardanza'), ('FALTA', 'Falta'), ('JUSTIFICADO', 'Justificado')], max_length=20),
        ),
    ]
