# Generated by Django 4.2 on 2024-11-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_asistencia_presente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='presente',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='criterios_asistencia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='puntaje_diario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador General'), ('FUA', 'Encargado JUA'), ('PRACTICAS', 'Encargado EFSRT'), ('COORDINADOR', 'Coordinador Academico'), ('SECRETARIA', 'Secretaria'), ('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante'), ('JURADO', 'Jurado Evaluador')], max_length=30),
        ),
    ]
