# Generated by Django 4.2 on 2024-12-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_asistencia_presente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='hora_salida',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='asistio',
            field=models.CharField(choices=[('ASISTIO', 'Asistió'), ('FALTA', 'Falta')], default='ASISTIO', max_length=10),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='puntualidad',
            field=models.CharField(choices=[('PUNTUAL', 'Puntual'), ('TARDANZA', 'Tardanza')], default='PUNTUAL', max_length=10),
        ),
    ]
