# Generated by Django 4.2 on 2024-12-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_asistencia_hora_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='codigo_estudiante',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='boleta_pago',
            field=models.FileField(blank=True, null=True, upload_to='boletas_pago/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fut',
            field=models.FileField(blank=True, null=True, upload_to='futs/'),
        ),
    ]
