# Generated by Django 4.2 on 2024-12-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_estudiante_codigo_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='criterios_evaluados',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('practica', 'jurado')},
        ),
    ]
