# Generated by Django 4.2 on 2024-12-08 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_evaluacion_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='evaluado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_evaluados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informe',
            name='fecha_evaluacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
