# Generated by Django 4.2 on 2024-12-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_informe_calificacion_informe_evaluado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='puntualidad',
            field=models.CharField(choices=[('PUNTUAL', 'Puntual'), ('TARDANZA', 'Tardanza'), ('FALTA', 'Falta')], default='PUNTUAL', max_length=10),
        ),
    ]
