# Generated by Django 4.2 on 2024-12-16 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_usuario_dni_alter_asistencia_puntualidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practica',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='practica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.practica'),
        ),
        migrations.AddField(
            model_name='practica',
            name='supervisores',
            field=models.ManyToManyField(limit_choices_to={'rol': 'DOCENTE'}, related_name='practicas_supervisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='asignaciondocente',
            unique_together={('docente', 'practica')},
        ),
    ]
