# Generated by Django 4.2 on 2024-12-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_practica_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practica',
            unique_together={('estudiante', 'modulo')},
        ),
    ]
