# Generated by Django 4.2 on 2024-12-18 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_practica_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='jurados',
            field=models.ManyToManyField(limit_choices_to={'rol': 'JURADO'}, related_name='practicas_evaluadas', through='api.AsignacionJurado', to=settings.AUTH_USER_MODEL),
        ),
    ]
