# Generated by Django 4.2 on 2024-12-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_practica_jurados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionjurado',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionjurado',
            unique_together={('practica', 'jurado')},
        ),
    ]
