name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: efsrt_db
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create and activate virtual environment
        run: |
          cd practicas_backend
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies (backend)
        run: |
          cd practicas_backend
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Debug current directory
        run: |
          pwd
          ls -R
          cd practicas_backend
          pwd
          ls -R

      - name: Django migrations
        run: |
          cd practicas_backend
          source venv/bin/activate
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Django tests
        run: |
          cd practicas_backend
          source venv/bin/activate
          python manage.py test

  # Job para el frontend (React + Vite)
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies (frontend)
        run: |
          cd practicas_frontend || exit 1
          npm install

      - name: Build frontend
        run: |
          cd practicas_frontend || exit 1
          npm run build

      - name: Run frontend tests
        run: |
          cd practicas_frontend || exit 1
          npm test
