name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: efsrt_db
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug current directory
        run: |
          echo "Directorio actual: $(pwd)"
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies (backend)
        run: |
          cd Sistema-EFSRT/practicas_backend || exit 1
          pip install -r requirements.txt

      - name: Verify manage.py exists
        run: |
          if [ ! -f "Sistema-EFSRT/practicas_backend/manage.py" ]; then
            echo "Error: manage.py no encontrado en Sistema-EFSRT/practicas_backend"
            exit 1
          fi

      - name: Django migrations
        run: |
          cd Sistema-EFSRT/practicas_backend || exit 1
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Django tests
        run: |
          cd Sistema-EFSRT/practicas_backend || exit 1
          python manage.py test


  # Job para el frontend (React + Vite)
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies (frontend)
        run: |
          cd practicas_frontend || exit 1
          npm install

      - name: Build frontend
        run: |
          cd practicas_frontend || exit 1
          npm run build

      - name: Run frontend tests
        run: |
          cd practicas_frontend || exit 1
          npm test
