name: Deploy Django-React App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: efsrt_db
          MYSQL_ROOT_PASSWORD: root
        ports:
          - '3306:3306'
        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=20s
          --health-timeout=10s
          --health-retries=10
          --health-start-period=40s

    steps:
    - uses: actions/checkout@v2
    
    - name: Verificar MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
          sleep 1
        done
