name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job para el backend (Django REST Framework)
  backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: efsrt_db
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies (backend)
        run: |
          cd Sistema-EFSRT/practicas_backend || exit 1
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "DATABASE_NAME=efsrt_db" >> $GITHUB_ENV
          echo "DATABASE_USER=root" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=" >> $GITHUB_ENV
          echo "DATABASE_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DATABASE_PORT=3306" >> $GITHUB_ENV

      - name: Verify manage.py location
        run: |
          if [ ! -f "Sistema-EFSRT/practicas_backend/manage.py" ]; then
            echo "Error: manage.py no encontrado en Sistema-EFSRT/practicas_backend"
            exit 1
          fi

      - name: Django migrations
        run: |
          cd Sistema-EFSRT/practicas_backend || exit 1
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Django tests
        run: |
          cd Sistema-EFSRT/practicas_backend || exit 1
          python manage.py test

  # Job para el frontend (React + Vite)
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies (frontend)
        run: |
          cd Sistema-EFSRT/practicas_frontend || exit 1
          npm install

      - name: Build frontend
        run: |
          cd Sistema-EFSRT/practicas_frontend || exit 1
          npm run build

      - name: Run frontend tests
        run: |
          cd Sistema-EFSRT/practicas_frontend || exit 1
          npm test
