name: Deploy Django-React App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Deploy Backend
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py collectstatic --noinput

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Build Frontend
      run: |
        cd practicas_frontend
        npm install
        npm run build
