name: Deploy Django-React App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: efsrt_db
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: no
        ports:
          - '3306:3306'
        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=20s
          --health-timeout=10s
          --health-retries=10

    steps:
    - uses: actions/checkout@v2
    
    - name: Esperar MySQL
      run: |
        timeout 30s bash -c "until mysql -h127.0.0.1 -uroot -proot -e 'SELECT 1;'; do sleep 2; done"
