name: Deploy Django-React App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: efsrt_db
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_HOST: localhost
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Debug Directory Structure
        run: |
          pwd
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          cd $GITHUB_WORKSPACE
          ls -la
          cd practicas_backend
          ls -la
          pip install -r requirements.txt

      - name: Run Migrations
        env:
          DJANGO_SETTINGS_MODULE: practicas_backend.settings
          DB_NAME: efsrt_db
          DB_USER: root
          DB_PASSWORD: ""
          DB_HOST: localhost
        run: |
          cd practicas_backend
          python manage.py migrate
          python manage.py collectstatic --noinput

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Build Frontend
        run: |
          cd practicas_frontend
          npm install
          npm run build
